wireguard:
  wireguard:
    clients:
      - PublicKey: vln51Hq6I8orezoNmNnc4GG1GVxYUTZFwHuTPBgd3Fg=
        AllowedIPs: 0.0.0.0/0
      - PublicKey: 1aK3qzo6IjnxnuZrV7mLd2MMm+Xw83UCvBbKNQIzETk=
        AllowedIPs: 0.0.0.0/0
  service:
    type: NodePort
