wireguard:
  wireguard:
    serverAddress: 172.32.32.1/24
    serverCidr: 172.32.32.0/24
    clients:
      - PublicKey: vln51Hq6I8orezoNmNnc4GG1GVxYUTZFwHuTPBgd3Fg=
        AllowedIPs: 172.32.32.2/32
      - PublicKey: 1aK3qzo6IjnxnuZrV7mLd2MMm+Xw83UCvBbKNQIzETk=
        AllowedIPs: 172.32.32.3/32
  service:
    type: NodePort
