wireguard:
  wireguard:
    clients:
      - PublicKey: vln51Hq6I8orezoNmNnc4GG1GVxYUTZFwHuTPBgd3Fg=
        AllowedIPs: 10.34.0.2/32
      - PublicKey: 1aK3qzo6IjnxnuZrV7mLd2MMm+Xw83UCvBbKNQIzETk=
        AllowedIPs: 10.34.0.3/32
  service:
    type: NodePort
  disablePrivateKeyManagement: true
